name: middleware-unit-tests


on:
  push:
    branches: main


jobs:
  mw-unit-tests:
    runs-on: ubuntu-latest
    env:
      #mw_path: /usr/lib/python3/dist-packages/middlewared
      mw_path: /usr/local/lib/python3.8/dist-packages/middlewared

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup pytest
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo pip3 install pytest Babel

    - name: Checkout middleware repo
      uses: actions/checkout@v2

    - name: What version of Ubuntu are we running
      run: uname -a

    - name: Install middleware
      run: |
        cd $GITHUB_WORKSPACE/src/middlewared
        sudo python3 ./setup.py install

    - name: Copy unit tests into dist-packages
      run: |
        cd $GITHUB_WORKSPACE/src/middlewared/middlewared
        tar cfp - ./pytest | (cd $mw_path ; sudo tar xfp -)

    - name: Verify copy was successful
      run: |
        md5sum $GITHUB_WORKSPACE/src/middlewared/middlewared/pytest/client.py
        md5sum $mw_path/pytest/client.py

    - name: Install pytest dependencies
      run: |
        cd $mw_path/pytest
        pip install -r unit/requirements.txt
        pip install asynctest

    - name: middleware unit tests
      run: |
        cd $mw_path/pytest
        pytest unit
