name: middleware-unit-tests

on:
  push:
    branches: main

  #  pull_request:
  #  types:
  #    - 'opened'
  #    - 'synchronize'

jobs:
  mw-unit-tests:
    runs-on: ubuntu-latest
    env:
      mw_path: /usr/lib/python3/dist-packages/middlewared

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup pytest
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo pip3 install pytest

    - name: Checkout middleware & copy tests
      uses: actions/checkout@v2

    - name: What version of Ubuntu are we running
      run: uname -a

    - name: Checkout middleware & copy tests
      run: |
        sudo mkdir -p $mw_path
        cd $GITHUB_WORKSPACE/src/middlewared/middlewared
        tar cfp - ./pytest | (cd $mw_path ; sudo tar xfp -)

    - name: Verify copy was successful
      run: |
        md5sum $GITHUB_WORKSPACE/src/middlewared/middlewared/pytest/client.py
        md5sum $mw_path/pytest/client.py


        #    - name: Finalize dependencies
        #      run: |
        #        cd $mw_path/pytest
        #        pip install -r unit/requirements.txt
        #        pip install asynctest

